### ISSUE TITLE
[Feature request] Implement Unversioned Preferred Python Path

### ISSUE THREAD

**Issue by ghost** [mgorny/python-exec#14]
# Description of the problem
When python-exec is used to create Python virtual environments (venv) `python -m venv path`, the resulting pyvenv.cfg in the venv directory includes version-specific information for the Python used at creation time.

```
gheeman@gentoo ~ $ python -m venv .emacs.venv
gheeman@gentoo ~ $ cat .emacs.venv/pyvenv.cfg 
home = /usr/lib/python-exec/python3.13
include-system-site-packages = false
version = 3.13.1
executable = /usr/bin/python3.13
command = /usr/lib/python-exec/python3.13/python -m venv /home/gheeman/.emacs.venv
```

This paths including the version information does not align well with the default system selection of Python, which may have been upgraded later, and the venv can be upgraded later using the "--upgrade" flag `python3 -m venv --upgrade ENV_DIR`

Setting the venv configuration to unknown Python versions seems to work but has the effect of selecting a different Python version than the one preferred by the system:
```
gheeman@gentoo ~/.emacs.venv $ cat pyvenv.cfg 
home = /usr/lib/python-exec/python9.13
include-system-site-packages = false
version = 9.13.1
executable = /usr/bin/python9.13
command = /usr/lib/python-exec/python9.13/python -m venv /home/gheeman/.emacs.venv
gheeman@gentoo ~/.emacs.venv $ source bin/activate
(.emacs.venv) gheeman@gentoo ~/.emacs.venv $ python --version
Python 3.12.8
```

Buit as you can see, the selection of Python in the venv is not the preferred system selection:
```
gheeman@gentoo ~ $ python --version
Python 3.13.1
gheeman@gentoo ~ $ cat /etc/python-exec/python-exec.conf 
python3.13
python3.12
gheeman@gentoo ~ $ eselect python list
Available Python interpreters, in order of preference:
  [1]   python3.13
  [2]   python3.12
  [3]   python3.11 (fallback)
```

The venv somehow selects the python version configured in Portage
```
gheeman@gentoo ~/.emacs.venv $ emerge --info | grep -i python
Portage 3.0.66.1 (python 3.12.8-final-0, default/linux/amd64/23.0/no-multilib/systemd, gcc-14, glibc-2.40-r5, 6.12.4-gentoo-dist x86_64)
dev-lang/python:           3.11.11_p1::gentoo, 3.12.8::gentoo, 3.13.1::gentoo
```

# Proposal
Provide a /usr/lib/python-exec/python symlink to the preferred system selection, from which Python is executed without version information in the paths, so that venvs and other things are configured to the preferred system selection.

**Comment by mgorny** [comment]
I fail to understand what the problem is.

```console
$ rm -rf venv/
$ python3.10 -m venv venv
$ cat venv/pyvenv.cfg 
home = /usr/bin
include-system-site-packages = false
version = 3.10.16
$ python3.13 -m venv --upgrade venv
$ cat venv/pyvenv.cfg 
home = /usr/bin
include-system-site-packages = false
version = 3.13.1
executable = /usr/bin/python3.13
command = /usr/bin/python3.13 -m venv --upgrade /tmp/venv
```

**Comment by ghost** [comment]
That you need to issue the command to upgrade venvs manually.

Never mind, it is probably a bad idea to have a venv without a specific version of Python.

**Comment by mgorny** [comment]
Yes, it is. If you switch Python without explicitly upgrading venv, you're going to have site packages for the wrong version.
