### ISSUE TITLE
python-exec suppresses script output

### ISSUE THREAD

**Issue by thornecc** [mgorny/python-exec#4]
I am trying to install the TensorFlow package for R. The build process involves running a Python script and on Gentoo, R automatically tries to run the script with python-exec. This causes the build to fail since it tries to parse the output of the script, but python-exec seems to suppress this output.

As a minimal example, running test.py:
```python
print('Hello World!')
```
in python-exec:
```sh
alex@cizin ~ $ python-exec2c ./test.py
alex@cizin ~ $
```

Is this the desired behaviour? Is there any way to recover the output?

**Comment by mgorny** [comment]
This is not a valid use of `python-exec2c`. It doesn't suppress any output, it just doesn't run the script. If you look at `$?`, you'd notice it exited with 127 -- aka it doesn't find wrapped script to run.

**Comment by thornecc** [comment]
Sorry -- should have RTFM. Thanks for replying.
